### ISSUE TITLE
Problems since HASS version 1.32.1

### ISSUE THREAD

**Issue by joshuavandermeulen** [michaelarnauts/home-assistant-comfoconnect#23]
Intergration stops working after +- day after updating HAS to newest version and integration to newest version.
After restarting HASS it works again. Reloading integration does not help.
HASS version: 1.32.1

**At this point in the log it starts going wrong:**

2023-08-23 05:44:30.255 DEBUG (SyncWorker_5) [custom_components.comfoconnect.sensor] Handle update for sensor Supply fan speed (122): 908
2023-08-23 05:44:31.286 DEBUG (MainThread) [aiocomfoconnect.bridge] RX 00000000002910158001144fd71e22e1 -> 1ce695b3cf5970413164d4ae00922dbd: 0828 087a12028603
type: CnRpdoNotificationType

pdid: 122
data: "\206\003"

2023-08-23 05:44:32.289 DEBUG (MainThread) [aiocomfoconnect.bridge] RX 00000000002910158001144fd71e22e1 -> 1ce695b3cf5970413164d4ae00922dbd: 0828 087a12028103
type: CnRpdoNotificationType

pdid: 122
data: "\201\003"

2023-08-23 05:44:33.310 DEBUG (MainThread) [aiocomfoconnect.bridge] RX 00000000002910158001144fd71e22e1 -> 1ce695b3cf5970413164d4ae00922dbd: 0828 087a12027f03
type: CnRpdoNotificationType

pdid: 122
data: "\177\003"

2023-08-23 05:44:34.309 DEBUG (MainThread) [aiocomfoconnect.bridge] RX 00000000002910158001144fd71e22e1 -> 1ce695b3cf5970413164d4ae00922dbd: 0828 087a12028203
type: CnRpdoNotificationType

pdid: 122
data: "\202\003"

2023-08-23 05:44:35.320 DEBUG (MainThread) [aiocomfoconnect.bridge] RX 00000000002910158001144fd71e22e1 -> 1ce695b3cf5970413164d4ae00922dbd: 0828 087a12028903
type: CnRpdoNotificationType

pdid: 122
data: "\211\003"

2023-08-23 05:44:51.229 ERROR (MainThread) [homeassistant.components.mill] Timeout fetching mill data
2023-08-23 05:44:52.348 DEBUG (MainThread) [custom_components.comfoconnect] Sending keepalive...
2023-08-23 05:44:52.348 DEBUG (MainThread) [aiocomfoconnect.bridge] CnTimeRequest
2023-08-23 05:44:52.348 DEBUG (MainThread) [aiocomfoconnect.bridge] Adding listener for event 157
2023-08-23 05:44:52.348 DEBUG (MainThread) [aiocomfoconnect.bridge] TX 1ce695b3cf5970413164d4ae00922dbd -> 00000000002910158001144fd71e22e1: 081e209d01 
type: CnTimeRequestType
reference: 157

2023-08-23 05:44:52.350 DEBUG (MainThread) [aiocomfoconnect.bridge] CnRmiRequest
2023-08-23 05:44:52.350 DEBUG (MainThread) [aiocomfoconnect.bridge] Adding listener for event 158
2023-08-23 05:44:52.350 DEBUG (MainThread) [aiocomfoconnect.bridge] TX 1ce695b3cf5970413164d4ae00922dbd -> 00000000002910158001144fd71e22e1: 0821209e01 0801120483150601
type: CnRmiRequestType
reference: 158

nodeId: 1
message: "\203\025\006\001"

2023-08-23 05:44:55.296 DEBUG (MainThread) [aiocomfoconnect.bridge] RX 00000000002910158001144fd71e22e1 -> 1ce695b3cf5970413164d4ae00922dbd: 0828 087a12028f03
type: CnRpdoNotificationType

pdid: 122
data: "\217\003"
2023-08-23 05:44:55.297 DEBUG (SyncWorker_3) [custom_components.comfoconnect.sensor] Handle update for sensor Supply fan speed (122): 911
2023-08-23 05:44:57.351 WARNING (MainThread) [aiocomfoconnect.bridge] Timeout while waiting for response from bridge
2023-08-23 05:44:57.352 DEBUG (MainThread) [aiocomfoconnect.bridge] Disconnecting from bridge 192.168.0.30
2023-08-23 05:44:57.353 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiocomfoconnect/bridge.py", line 168, in _send
    return await asyncio.wait_for(fut, TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/comfoconnect/__init__.py", line 151, in send_keepalive
    await bridge.cmd_time_request()
  File "/usr/local/lib/python3.11/site-packages/aiocomfoconnect/bridge.py", line 171, in _send
    raise AioComfoConnectTimeout from exc
aiocomfoconnect.exceptions.AioComfoConnectTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/comfoconnect/__init__.py", line 158, in send_keepalive
    await bridge.connect(entry.data[CONF_LOCAL_UUID])
  File "/usr/local/lib/python3.11/site-packages/aiocomfoconnect/comfoconnect.py", line 70, in connect
    await super().connect(uuid)
  File "/usr/local/lib/python3.11/site-packages/aiocomfoconnect/bridge.py", line 94, in connect
    await self.disconnect()
  File "/usr/local/lib/python3.11/site-packages/aiocomfoconnect/bridge.py", line 121, in disconnect
    await self._read_task
  File "/usr/local/lib/python3.11/site-packages/aiocomfoconnect/bridge.py", line 213, in _read_messages
    message = await self._read()
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiocomfoconnect/bridge.py", line 175, in _read
    msg_len_buf = await self._reader.readexactly(4)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 729, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 522, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 989, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by joshuavandermeulen** [comment]
Thanks in advance. And take care!

**Comment by joshuavandermeulen** [comment]
@michaelarnauts did you already have time to look into this problem?

**Comment by michaelarnauts** [comment]
I'm sorry, I haven't looked at it yet. I haven't noticed the issue myself since last time however.

**Comment by joshuavandermeulen** [comment]
Good to know! On what version are you?

**Comment by joshuavandermeulen** [comment]
I tried updating to 2023.10.3 without succes. Same issues. So I had to restore a back-up.

**Comment by michaelarnauts** [comment]
@joshuavandermeulen Could it be that your DHCP lease is one day, and that your Comfoconnect LAN C is getting a different IP?

**Comment by joshuavandermeulen** [comment]
Nope, DHCP lease is not one day. I even made a DHCP reservation just to be sure.

**Comment by michaelarnauts** [comment]
Closing since I want to migrate all these issues in one issue. See https://github.com/michaelarnauts/home-assistant-comfoconnect/issues/43 for a possible solution and follow-up.
