### ISSUE TITLE
Integration won't load with HA 2024.2.1 / HA OS 11.5

### ISSUE THREAD

**Issue by LavermanJJ** [michaelarnauts/home-assistant-comfoconnect#37]
## Description

After upgrading to Home-Assistant OS 11.5 the comfoconnect integration won't load. The logs show the following error. 

## Steps taken
* Removed that custom component and re-downloaded it
* Removing the integration and re-add it, isn't possible, as HA cannot load the integration at all. As a "work-around" I tried deactivating the integration and activate it again after a reboot
* In addition, I've changed the reference to aicomfoconnect from `0.1.8` to `0.1.9`

Unfortunately, non of the above was able to fix it. 

If there are any further information needed, I'm happy to provide them. 

Thanks! :)

## Home Assistant Log

```
Logger: homeassistant.loader
Source: loader.py:827
First occurred: 21:58:01 (1 occurrences)
Last logged: 21:58:01

Unexpected exception importing component custom_components.comfoconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/comfoconnect/__init__.py", line 7, in <module>
    from aiocomfoconnect import ComfoConnect, discover_bridges
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/__init__.py", line 3, in <module>
    from .bridge import Bridge  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 26, in <module>
    from .protobuf import zehnder_pb2
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/protobuf/zehnder_pb2.py", line 15, in <module>
    import nanopb.generator.proto.nanopb_pb2 as nanopb__pb2
  File "/usr/local/lib/python3.12/site-packages/nanopb/generator/proto/__init__.py", line 10, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

## System
home-assistant-comfoconnect version: [e7132a7](https://github.com/michaelarnauts/home-assistant-comfoconnect/commit/e7132a711e341534227b6e3e1d06568d530d135f) 

```
Core 2024.2.1
Supervisor 2024.01.1
Operating System 11.5
Frontend 20240207.1
```

**Comment by LavermanJJ** [comment]
It was caused by another integration that required an incompatible version of setuptools
