### ISSUE TITLE
Unknown error occurred when setting up integration

### ISSUE THREAD

**Issue by Testingfor101** [michaelarnauts/home-assistant-comfoconnect#53]
Hello,

I am using ComfoConnect PRO device, Product Number: 30006323.
With every version of this integration I get the same error.

Here is the log after failed integration:

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:146
First occurred: 10:15:30 PM (2 occurrences)
Last logged: 10:26:30 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 213, in _process_message
    message = await self._read()
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 176, in _read
    msg_len_buf = await self._reader.readexactly(4)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 750, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 4 expected bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 108, in _read_messages
    await self._process_message()
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 247, in _process_message
    raise AioComfoConnectNotConnected
aiocomfoconnect.exceptions.AioComfoConnectNotConnected

------------------- -----------------------------------------------------------------------------------------------------
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 10:15:30 PM (2 occurrences)
Last logged: 10:26:30 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 168, in _send
    return await asyncio.wait_for(fut, TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 88, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 71, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 356, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 402, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 506, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comfoconnect/config_flow.py", line 68, in async_step_user
    return await self._register()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comfoconnect/config_flow.py", line 133, in _register
    await self.bridge.cmd_start_session(True)
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 172, in _send
    raise AioComfoConnectTimeout from exc
aiocomfoconnect.exceptions.AioComfoConnectTimeout

**Comment by michaelarnauts** [comment]
Is the Comfoconnect Pro something like a Comfoconnect Lan C? I have never heard of it, and I don't know if it is compatible. According to your log, it seems like it's using a different protocol.

Or do you still have a Comfoconnect Lan C, and is the Comfoconnect Pro something else?

**Comment by Testingfor101** [comment]
Comfoconnect PRO looks like new version of LAN C.

**Comment by goncalossilva** [comment]
I have one of these newer devices. Do you recommend one particular method or app for capturing packets? And what action(s) should I perform when capturing?

**Comment by michaelarnauts** [comment]
On the original Comfoconnect, the local communication between the app and the device is unencrypted.

Some of the possibilities to capture the traffic:
* Run an android emulator with the app in your computer and capture the traffic it makes.
* Use a network switch with port mirroring, and mirror the port that is connected to the Comfoconnect to a computer that captures the traffic.
* Use a wireless hotspot that stores the traffic it passes.

You'll end up with a pcap you can open in Wireshark. Prepare for a lot of evenings staring at hex values trying to figure out how it works. This is how I did it for the original Comfoconnect. It took a lot of time.

Some tips:
* Make multiple captures of the same action (setting fan speed for example) and check for similarities in the captures.
* Read the protocol docs of the aiocomfoconnect repo. This is applicable on the actual Ventilation Unit, so it should match for the Comfoconnect Pro.
* If you are lucky, the Comfoconnect Pro does more abstraction, and supplies nice API's you can call.
* If the traffic between the app and the Comfoconnect Pro is encrypted, you should look at mitmproxy, there are guides online in how go remove the certificate pinning from the APK.

Good luck!

**Comment by Unloadable** [comment]
should be easy. 
"Global management and smart home solutions: The ComfoConnect PRO enables easy integration into smart home systems and offers automation protocols such as Modbus RTU/TCP."

[Link](https://www.zehnder-systems.ch/de/komfortable-raumlueftung/produkte/zubehoer-lueftungsgeraet/schnittstellen-connectivity/zehnder-comfoconnect-pro)

**Comment by szbartnik** [comment]
> Comfoconnect PRO looks like new version of LAN C.

Sorry for off topic @Testingfor101 but how you got the new ComfoConnect Pro? 

It's still not available in official distribution - asked Zehnder representatives few weeks ago.

**Comment by schoeni86** [comment]
Is there any news for comfoconnect pro module?

**Comment by michaelarnauts** [comment]
I don't have a Comfoconnect Pro. So I can't help here unfortunately.

**Comment by szbartnik** [comment]
I'm keen to buy one if anybody knows how to get it.

**Comment by goncalossilva** [comment]
I mentioned [above](https://github.com/michaelarnauts/home-assistant-comfoconnect/issues/53#issuecomment-2242454014) I had one of the newer devices, but I actually don't know if it's a Comfoconnect Pro or similar to it. It's an Arduino-based device:

![image](https://github.com/user-attachments/assets/8d92e560-03b7-429b-81b8-8599ea1d66bd)

It came together with my ComfoClime unit. It looks like a [stripped down version of the real thing](file:///Users/goncalossilva/Downloads/Zehnder_CSY_ComfoConnect-PRO_DAS_UK-en.pdf), but I could be mistaken.

I've been meaning to reverse engineer the corresponding Android app (by capturing traffic or decompiling the APK and see what I can figure out) but I've lacked the time to do so, unfortunately.

**Comment by schoeni86** [comment]
I definitely have the Pro module.

![IMG_8353](https://github.com/user-attachments/assets/ed46ff88-0832-4e54-b884-0e8b73b3a150)

maybe you can buy it [here](https://www.epicair.co.uk/products/zehnder-comfoconnect-pro-for-comfoair-q350-450-600-and-flex?_pos=8&_sid=70b69caf9&_ss=r).

**Comment by Testingfor101** [comment]
> > Comfoconnect PRO looks like new version of LAN C.
> 
> Sorry for off topic @Testingfor101 but how you got the new ComfoConnect Pro?
> 
> It's still not available in official distribution - asked Zehnder representatives few weeks ago.

That was my client which had opportunity to get one, I am just providing integrations of devices.

**Comment by msfuture** [comment]
> I mentioned [above](https://github.com/michaelarnauts/home-assistant-comfoconnect/issues/53#issuecomment-2242454014) I had one of the newer devices, but I actually don't know if it's a Comfoconnect Pro or similar to it. It's an Arduino-based device:
> 
> ![image](https://github.com/user-attachments/assets/8d92e560-03b7-429b-81b8-8599ea1d66bd)
> 
> It came together with my ComfoClime unit. It looks like a stripped down version of the real thing, but I could be mistaken.
> 
> I've been meaning to reverse engineer [the corresponding Android app](https://play.google.com/store/apps/details?id=com.zehndergroup.comfocontrolmobile) (by capturing traffic or decompiling the APK and see what I can figure out) but I've lacked the time to do so, unfortunately.

The API on the ComfoClime hardware is an unencrypted REST Interface. Most of the datapoints are already known, as they're similar to the ComfoConnect LANC. 
I tried to document the Interface including the ComfoClime specific values a few weeks ago:

https://github.com/msfuture/comfoclime_api

**Comment by Puekcommander** [comment]
Hi,

I own a Comfoclime 24, but I’ve noticed that it’s running a bit slow in terms of power. As far as I know, the Comfoclime 24 and 36 have the same hardware/compressor etc. Has anyone tried setting switch to 0 (1 for the 24), so that it runs on the power management of the Comfoclime 36? 

Thanks in advance for your responses!

**Comment by MongerGodfrey87** [comment]
Good evening. I need to order the LAN control module, but wanted to make sure I get a compatible one. Did anyone get the Pro version working, or should I still order the older LAN C?

**Comment by msfuture** [comment]
At least the official app ist the same for the pro Version. Good chance that the protocol didn't change. 
I will not switch to the new one as the ComfoClime unit has a very good working JSON Interface for the whole ComfoNet bus and I built a integration for that.

**Comment by MongerGodfrey87** [comment]
Thanks Michael, that's helpful. I guess it makes sense to stick with the older one for now in that new case as I know that's reliable.

**Comment by msfuture** [comment]
If you don't need a modbus interface to your unit, I can see no advantage of the newer (and maybe more expensive) one. 

@goncalossilva It looks like you have a ComfoClime unit. I have built an integration for these devices here: [HACS ComfoClime](https://github.com/msfuture/comfoclime)

**Comment by goncalossilva** [comment]
@Puekcommander correct, ComfoClime Q.

**Comment by Puekcommander** [comment]
Can someone show me the board and wires of the comfoclime 36? I am still searching if it’s possible to set the comfoclime 24 on the dipswitch to run on the power levels of the 36.

**Comment by JustinWingChungHui** [comment]
The Comfoconnect LAN C is now discontinued.  I just tried to order one and was told they are no longer in stock and won't be manufacturing any more.

Looks like I'll be getting the Pro soon.  Hopefully, I might be able inspect the traffic

**Comment by Chrisl1710** [comment]
Is there now a solution for the ComfoConnect Pro? I have that too and a ComfoClime and don't get both connected: "Unexpected mistake" And i can't find any other solution that works, i even tried woth modbus and failed.

**Comment by simonwestenholz** [comment]
> The Comfoconnect LAN C is now discontinued.  I just tried to order one and was told they are no longer in stock and won't be manufacturing any more.
> 
> Looks like I'll be getting the Pro soon.  Hopefully, I might be able inspect the traffic

I am in the same boat. I already have a q350 in my basement with the LAN C, so tried ordering that for my new attic unit, but was told the same. I have a ComfoConnect Pro on the way.

**Comment by BernoldNL** [comment]
There is this PDF from Zehnder about connectivity. I noticed on the Belgian version from 2024-04-09 they mention for the ComfoConnect Pro: "Future proof voor connectie met Smart Home protocollen (nog niet beschikbaar)" Translated: "Future proof for connecting with Smart Home protocols (not yet available).". So it looks like they have something planned.
Source: https://producten.zehnder.be/download/6546e79ce3db48fd8240bec6a9b09847 (page 4).

Otherwise you should be able to use Modbus TCP/RTU. The Modbus addresses are mentioned on the ComfoConnect Pro Technical Specifications PDF. Source: https://www.zehnder.co.uk/download/2a4fc36575614ebbb7f0d03fd6597df4

Haven't tried this yet. Just had a ComfoAir Q450 installed 2 weeks ago. Still looking for a good place to buy the ComfoConnect Pro. They seem to be in backorder everywhere as well. And prices are crazy as well (doubled or more).

**Comment by simonwestenholz** [comment]
I just got mine from homeperfect.de for €249, though it's not on their site yet. They ordered it for me as they were unable to obtain the LAN C.

**Comment by coreYalfons** [comment]
I also have the new ComfoConnect Pro and want to have it in HA. Is thre a solution in progress? Can I help or support in any direction?

**Comment by JustinWingChungHui** [comment]
I have the ComfoConnect android app running within my local network communicating with the Pro

I've tried capturing the traffic using PCAPdroid and HTTP Toolkit.  But the app doesn't work at all when they are turned on.

I've also noticed that the app doesn't work when VPN-ing into my home network.  Does the same happen when using the LAN-C?  Has anyone successfully managed to capture any traffic to the Pro?

**Comment by coreYalfons** [comment]
My App on iPhone is running without any errors. IOT things are in a seperated VLAN and Home Assistant is the same VLAN too. When I connectt from a different VLAN it is not showing me as local connected. The App on iOS will go through the WAN. As soon as I am connected to the IOT VLAN it will connect local.
It is possible to enable remote-support, then you get a PIN.
There is also the ZEHNDER LAB https://my.zehnder-systems.com/auth/login 
You can login and see your device there. I can see the Q350 but it says "no cloud". And the App also has no Option in the menu "cloud". (Alexa is also not finding the device)
I can only see under connection status, that the cloud is enabled...when you go here (https://zehnder-systems-de.zendesk.com/hc/de/articles/14434138497181-ComfoControl-App-Cloud-freischalten-Integration-in-Alexa-und-Google-Assistant) they are talking about ComfoControlApp with LAN-C Modul.
I will open a support case for Zehnder (-> ), maybe there is something not published to the fireware or app correctly for the Pro Lan device. For me it looks like.

<img width="263" height="439" alt="Image" src="https://github.com/user-attachments/assets/ee27fe1c-93ef-45ec-9ba3-c91f26a6f63c" />

<img width="450" height="839" alt="Image" src="https://github.com/user-attachments/assets/13aced60-86c5-444b-b6d3-e6a0d07d8f52" />

<img width="451" height="290" alt="Image" src="https://github.com/user-attachments/assets/2cd34863-93a3-4913-b4c2-87f51494e300" />

<img width="453" height="660" alt="Image" src="https://github.com/user-attachments/assets/37a091f8-4248-4fdd-8bcb-9893d54952f9" />

**Comment by coreYalfons** [comment]
And I just want to add this here, because Zehnder itself says 
**Interface for global management and smart home solutions: automation protocols
(Modbus RTU/TCP), local/remote app control via cloud, and technical support.
Free download of the Zehnder app (available in the App Store and Google Play Store under
"Zehnder ComfoControl")**

Thats they key to connect, like [BernoldNL](https://github.com/BernoldNL) already said.

<img width="691" height="392" alt="Image" src="https://github.com/user-attachments/assets/2b837748-5ccd-4b5e-a9e5-2b7e862aa2a6" />

**Comment by simonwestenholz** [comment]
I've set up the sensors in home assistant with modbus TCP, but it's not quite reliable, as a few of the sensors stop updating until I open the app on my phone. Additionally there are several sensors that I feel are missing, such as bypass state, power consumption and motor duty cycle amongst others. I hope we'll be able to communicate like we did with the LAN C, as that was a lot better.

**Comment by JustinWingChungHui** [comment]
> I've set up the sensors in home assistant with modbus TCP, but it's not quite reliable, as a few of the sensors stop updating until I open the app on my phone. Additionally there are several sensors that I feel are missing, such as bypass state, power consumption and motor duty cycle amongst others. I hope we'll be able to communicate like we did with the LAN C, as that was a lot better.

Would you be willing to share some of the YAML you used to set this up?  I've ordered a Modbus to Ethernet adaptor.

**Comment by BernoldNL** [comment]
> I've set up the sensors in home assistant with modbus TCP, but it's not quite reliable, as a few of the sensors stop updating until I open the app on my phone. Additionally there are several sensors that I feel are missing, such as bypass state, power consumption and motor duty cycle amongst others. I hope we'll be able to communicate like we did with the LAN C, as that was a lot better.

Wow, yes, those sensors are pretty basic. Did some Googling, but did not find additional information, yet. I don't have my ComfoConnect Pro yet. Ordered it today from heizung-billiger.de. Hope to be able to do some testing shortly after the weekend.

Meanwhile, does anybody have an idea in which country this is developed by Zehnder? (In other words, where do we have the most chance if we ask their support for this kind of information?

Edit: It looks like the developer of the Loxone template already asked these kind of questions
See: https://library.loxone.com/detail/zehnder-comfoconnect-pro-1768/support (I'm guessing he asked Zehnder Germany).

**Comment by simonwestenholz** [comment]
> Would you be willing to share some of the YAML you used to set this up? I've ordered a Modbus to Ethernet adaptor.

Sure. I've attached the yaml as a txt file. You don't need a modbus adapter for modbus TCP.

[modbus.yaml.txt](https://github.com/user-attachments/files/21763140/modbus.yaml.txt)

**Comment by simonwestenholz** [comment]
> I've set up the sensors in home assistant with modbus TCP, but it's not quite reliable, as a few of the sensors stop updating until I open the app on my phone. Additionally there are several sensors that I feel are missing, such as bypass state, power consumption and motor duty cycle amongst others. I hope we'll be able to communicate like we did with the LAN C, as that was a lot better.

Hmm, restarting the ComfoConnect Pro seems to have solved my issue with sensors that failed to update.

**Comment by coreYalfons** [comment]
I started to add something manuall by modbus in HA - looks very good but I need some time to bringt this in a good way

UPDATE: Ahhh, I saw that Simon already did some good work here too ;-)

I guess to avoid blocking the app you need to choose another slave id, it looks like the app is using the same ?

<img width="994" height="1445" alt="Image" src="https://github.com/user-attachments/assets/c96d4e99-b1a3-49ea-8629-1220d112eb6f" />

**Comment by simonwestenholz** [comment]
I don't think the app uses modbus. I'm not seeing any blocking issues, at least.

**Comment by szbartnik** [comment]
> > I've set up the sensors in home assistant with modbus TCP, but it's not quite reliable, as a few of the sensors stop updating until I open the app on my phone. Additionally there are several sensors that I feel are missing, such as bypass state, power consumption and motor duty cycle amongst others. I hope we'll be able to communicate like we did with the LAN C, as that was a lot better.
> 
> Hmm, restarting the ComfoConnect Pro seems to have solved my issue with sensors that failed to update.

A similar thing happened to me twice over the past few months with ComfoConnect Pro + Modbus (Loxone). Restarting fixed the problem.

**Comment by JustinWingChungHui** [comment]
> > Would you be willing to share some of the YAML you used to set this up? I've ordered a Modbus to Ethernet adaptor.
> 
> Sure. I've attached the yaml as a txt file. You don't need a modbus adapter for modbus TCP.
> 
> [modbus.yaml.txt](https://github.com/user-attachments/files/21763140/modbus.yaml.txt)

@simonwestenholz this is amazing!  Thank you!

This is working quite well for me, but it is missing Bypass which is pretty important.  Hopefully it will get added in.

**Comment by BernoldNL** [comment]
I hope leaving out stuff like Bypass is not by design or something. I was looking at the ComfoConnect KNX C documentation and they left it out there as well..

**Comment by NStrijbosch** [comment]
> I hope leaving out stuff like Bypass is not by design

I have contacted Zehnder support on this. Unfortunately the response I received was that this is a design choice: "Zehnder wants the unit to manage the bypass automatically based on the comfort temperature, since the bypass and preheater should prevent frost damage." 

They have noted down my wish from the market. (It will probably help if more request like this come in)

**Comment by coreYalfons** [comment]
That a good idea to push Zehnder to make bypass manual possible. I dont understand their fears, they only should make this value accessibly when outdoor temperaturs is on a minimum of 16°C or something like that.

I am struggeling with the switches for the modes. Are they working for you with autoupdating the last state?
For example: When you push or write VentilatorPresent1, it will overwrite the Auto mode for 2 hours. Unfortunatelly the 2 hours are not able to be overwritten or in other way available in the function code. As soon as the device changes back from "Manual Ventilator Stage 1" to Auto - it will not update the switch state in Home Assistant. Is there a way to overwrite the switch state in Home Assistant with the read value of holding register 1 (-> Ventilator Present state 0-3) ?

Update: OK here I just added something like (for boost) this to the switches. It will auto update the switch values then by the status pulled from the device. Nice.

      verify:
        address: 0
        state_on: 1
        state_off: 0
        delay: 10


I am also try to make a party mode possible by entering a duration. The Boost switch is currently not working for me. I guess it is missing a value for the duration too (boost time). Anybody any ideas how to create a button or a switch where we can add a input value like seconds or minutes to set the boost value and enable the boost with that duration? 


There is also a warning about the fan, I have no idea:

<img width="463" height="70" alt="Image" src="https://github.com/user-attachments/assets/6fe5f478-c18d-4e44-ae6d-e503fa56c23b" />

**Comment by BernoldNL** [comment]
They could just add such warnings to the documentation. Or even put the unit in some kind of error if you abuse it.
At the very least it should be available as read only. But let's not suggest it in that way.

I would love to be able to open the bypass in the evening with our current summer weather, to get as much colder air inside the house as possible. The unit does that quite late in my opinion, even with the "fast" setting.

**Comment by coreYalfons** [comment]
Here is a manual boost trigger by using a helper

<img width="552" height="916" alt="Image" src="https://github.com/user-attachments/assets/b83f4a0c-5868-47d1-8769-22a87c4c2930" />

automation.yaml

- id: '1755269570637'
  alias: Zehnder ComfoAirQ Automation Boost Trigger
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_number.boost_timer_set
  conditions: []
  actions:
  - action: modbus.write_register
    metadata: {}
    data:
      hub: zehnder
      slave: 1
      address: 4
      value: '{{ ((states.input_number.boost_timer_set.state)|float * 60 * 60) | int
        }}'
  - action: modbus.write_coil
    metadata: {}
    data:
      hub: zehnder
      address: 6
      state: 1
      slave: 1
  mode: single


<img width="594" height="342" alt="Image" src="https://github.com/user-attachments/assets/dd842734-1e2f-4318-92a1-48ecade94bcd" />

Any way to grey the timer slider out as long as the boost is active?
To set a new value, you should first disable the boost and then reset a value again.
Any ideas how it will be possible?

**Comment by JustinWingChungHui** [comment]
I got this response from Zehnder support about adding support for the bypass.

```
Thank you for your email.
 
So I can understand better, why would you want to manually control the bypass? If you set up the temperature profiles correctly, 
the bypass will work automatically and correctly. Manually engaging the bypass in the wrong situation i.e the wrong internal/
external temperature then the property could get hotter or colder than expected. It is best to let the unit control the bypass.
 
As you have the Connect Pro, you can connect to the unit with a smart phone and this has the bypass control on it. But again, 
refer to above.
 
It may be integrated later but there is no dates or confirmation that it ever will be.
```

**Comment by BernoldNL** [comment]
So they let you do it from the unit in the app and call that smart. 🤣

**Comment by coreYalfons** [comment]
we should write more mails to them.
We also want to know the **status of the bypass** in % in modbus. I guess you can overwrite the bypass at the moment by modify the temperature profiles via modbus. Set temperature mode to external setpoint and adust the temperature (holding register external setpoint).
But anyway: I miss energy values, value of heating unit, power consumption, rpm of the fans etc.

**Comment by BernoldNL** [comment]
Got my ComfoConnect Pro today. Did a port scan with nmap and found these ports open:

Port 22 TCP ssh Dropbear sshd 2020.81 (protocol 2.0) - Note that this is an old version, which has known vulnerabilities. It seems to have been removed after updating from D1.5.1. to R1.5.1.
Port 80 TCP http Kestrel - Obviously for the web interface
Port 5355 TCP llmnr - For the comfoconnectpro.local name
Port 56747 TCP  unknown - Which is what this integration/aiocomfoconnect uses(!)

Oh and UDP ports 68 (dhcp), 5353 (zeroconf), 5355 (llmnr). And more, but they seem different with every scan.

**Comment by ottermoosegoat** [comment]
Hello all,

Thanks for sharing on this thread!

The bypass issue seems like it could take longer to resolve (or be a deadend).

If we set bypass aside for a moment, what is the current state/outlook on other functions? Is Home Assistant working just as well now via a ComfoConnect **Pro** as it does via a ComfoConnect LAN C? @simonwestenholz have you seen new sensor update failures since your post of Aug 14?

I'm debating whether to buy a Pro or LAN C (both seem still available in the EU for similar prices).

Many thanks to all!

**Comment by damian1711** [comment]
there is another integration written for PRO model https://github.com/hstrohmaier/ha_comfoconnectpro
with both direct modubs and this integration i have same issues as others- sensor are not auto refreshed or only 1 temp sensor refresh but others not..sometimes few restarts reqiured..

**Comment by birill83** [comment]
I need to decide in whether buying the LAN or the PRO version. On one hand I’d prefer the PRO, also because if connects natively to the wifi, but then it seems the PRO integration is not yet well functioning ?

**Comment by simonwestenholz** [comment]
> Hello all,
> 
> Thanks for sharing on this thread!
> 
> The bypass issue seems like it could take longer to resolve (or be a deadend).
> 
> If we set bypass aside for a moment, what is the current state/outlook on other functions? Is Home Assistant working just as well now via a ComfoConnect **Pro** as it does via a ComfoConnect LAN C? @simonwestenholz have you seen new sensor update failures since your post of Aug 14?
> 
> I'm debating whether to buy a Pro or LAN C (both seem still available in the EU for similar prices).
> 
> Many thanks to all!

Sorry for the late reply. I haven't had issues since the initial problems. I do, however, prefer the way the LAN C works on my other unit, though. At least for now. It annoys me that so many sensors are simply not present, such as power consumption, bypass percentage and all the motor parameters. I like logging to see how the mechanisms interact. The only sensor I missed on the LAN C was the temperature before my post heater, to calculate the heat recovery efficiency. It's present in the app, so it's in there somewhere 😅

**Comment by birill83** [comment]
Can I have a general question: is it possible to only read parameters or control the unit too?

**Comment by simonwestenholz** [comment]
> Can I have a general question: is it possible to only read parameters or control the unit too?

Check out https://api.library.loxone.com/downloader/file/2218/Zehnder_CSY_ComfoConnect-Pro_INM_UK-en.pdf from page 21. The coils and holding registers are writable

**Comment by bugeaud** [comment]
Any one with pro version willing to make a packet capture of the pro sequences ? (pcap from tcpdump or wireshark) cc @schoeni86  @goncalossilva 

I would be very interrested to see the upgrade sequence of the pro module and also the upgrade sequence of the confoair done by the pro module.

As so far we have no way to keep the confoair up to date outside lanc or pro module.

**Comment by ottermoosegoat** [comment]
Short update from my end: I personally went with the ComfoConnect Pro. My primary need was to be able to set the fan speed programmatically, which I could easily achieve via modbus. It was also cheaper than the LAN C (I bought the Pro for 220EUR from [Selfio](https://www.selfio.de/produkte/zehnder-schnittstelle-comfoconnect-pro-wlan-fuer-lueftungsgeraete-q350-450-600)), and looked more future-proof.

I have not yet tried to integrate it with HA.

**Comment by michaelarnauts** [comment]
> Short update from my end: I personally went with the ComfoConnect Pro. My primary need was to be able to set the fan speed programmatically, which I could easily achieve via modbus. It was also cheaper than the LAN C (I bought the Pro for 220EUR from [Selfio](https://www.selfio.de/produkte/zehnder-schnittstelle-comfoconnect-pro-wlan-fuer-lueftungsgeraete-q350-450-600)), and looked more future-proof.
> 
> I have not yet tried to integrate it with HA.

Thanks for the update! I've read somewhere that Home Assistent could use its modbus integration to directly connect with the device. Feel free to post an update in case this works (or doesn't).

**Comment by BernoldNL** [comment]
Does anyone know what the "a" and "xr" values are in the Connection Status screen of the ComfoControl App (iOS in my case). They are hidden, but appear when you push about 2 lines under the visible info. I'm hoping they can be used as an alternative way to get the connection information for a Pro that comes from UDP port 56747 on a LAN C.

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/cb99f5e9-d0d9-46f2-9ddb-f9fb6841c343" />

**Comment by RobXYZ** [comment]
I created PR #133  with ComfoConnect Pro support. Would be good to know if it works for others.

**Comment by michaelarnauts** [comment]
A lot has moved here. The library supports the Pro since michaelarnauts/aiocomfoconnect#74: it recognises the gateway type from the discovery response, and registers on a Pro without starting a session first, which is what the Pro needs.

On this side, the config flow now uses that (#160), and the re-authentication step looks the bridge up through discovery as well (#162), so the type is detected there too. That last one matters for a Pro, since re-authentication happens exactly when the app is no longer registered.

Nobody with a Pro has confirmed it end to end though, which is why I am not closing this. If someone in this thread can try the pre-release and report what happens, that would settle it.

Could you try [v0.5.0-rc1](https://github.com/michaelarnauts/home-assistant-comfoconnect/releases/tag/v0.5.0-rc1)? In HACS, turn on "Show beta versions" in the download dialog to get it. If it still happens, a debug log would help, with `custom_components.comfoconnect: debug` and `aiocomfoconnect: debug` under `logger:`.

**Comment by mgupta80** [comment]
Hi @michaelarnauts I am still being redirected to connect to ComfoConnect LAN C:

<img width="875" height="497" alt="Image" src="https://github.com/user-attachments/assets/a1b12694-0e94-4f8d-95c0-f5797ee110f8" />

Below are the contents of manifest.json file:

{
  "domain": "comfoconnect",
  "name": "Zehnder ComfoAir Q",
  "config_flow": true,
  "dependencies": ["network"],
  "documentation": "https://www.home-assistant.io/integrations/comfoconnect",
  "integration_type": "hub",
  "requirements": ["aiocomfoconnect==0.2.1"],
  "codeowners": ["@michaelarnauts"],
  "iot_class": "local_push",
  "loggers": ["aiocomfoconnect"],
  "version": "0.5.0-rc1"
}

**Comment by NStrijbosch** [comment]
@michaelarnauts on my side the pre release is working as expected with two pro devices.

**Comment by mgupta80** [comment]
Hi @NStrijbosch, I am curious that your setup is working with Comfo Connect Pro and mine is not. It's taking me to the Comfo Connect LAN C screen and I could not see any error logs either on HA system logs.

Am I missing any steps for discovery of Comfo Connect Pro?

**Comment by NStrijbosch** [comment]
@mgupta80 I did not do add them through the UI. I included the following to my configuration.yml

```
comfoconnect:
  host: IP_ADDRESS_1
  host: IP_ADDRESS_2
```

**Comment by JustinWingChungHui** [comment]
I couldn't get past the PIN screen using the v0.5.0-rc1

<img width="722" height="435" alt="Image" src="https://github.com/user-attachments/assets/b9a33a22-a4c0-45ab-a135-839ae6a38747" />



<img width="722" height="412" alt="Image" src="https://github.com/user-attachments/assets/cd0a966b-fb35-449d-a672-79fb7d3ae446" />

**Comment by mgupta80** [comment]
Thanks @NStrijbosch, I tried to add the ComfoConnect Pro ip to configuration.yaml under homeassistant but it does not seems to work for me.

<img width="555" height="495" alt="Image" src="https://github.com/user-attachments/assets/7440cc85-57e8-404d-aac9-8cfb6ab59144" />

**Comment by NStrijbosch** [comment]
@mgupta80 to be complete I also did a home assistant restart.

**Comment by mgupta80** [comment]
@NStrijbosch, yes I did restart after making changes in configuration.yaml but it didn't work.

**Comment by michaelarnauts** [comment]
Are you sure you are using the pre-release integration? It doesn't support yaml config as far as I remember.

**Comment by NStrijbosch** [comment]
@michaelarnauts that makes me doubt myself, but see my screenshot below. 
Both devices are noted as LAN-C, but i am sure they are the pro. 

I will delete the yaml and see what happens if i follow the process through the UI.  
- Outcome: Through the UI the setup is also smooth. 

<img width="1052" height="710" alt="Image" src="https://github.com/user-attachments/assets/5a66f7ad-96fe-4a3a-a306-ed8651eac619" />
