### ISSUE TITLE
Integration Stopped working no changes made to environment.

### ISSUE THREAD

**Issue by jpdacostaza** [michaelarnauts/home-assistant-comfoconnect#80]
Configuration warnings
Platform error 'sensor' from integration 'comfoconnect' - cannot import name 'runtime_version' from 'google.protobuf' (/usr/local/lib/python3.12/site-packages/google/protobuf/__init__.py)

———

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 4:52:01 PM (1 occurrences)
Last logged: 4:52:01 PM

Setup failed for custom integration 'comfoconnect': Unable to import component: cannot import name 'runtime_version' from 'google.protobuf' (/usr/local/lib/python3.12/site-packages/google/protobuf/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/comfoconnect/__init__.py", line 8, in <module>
    from aiocomfoconnect import ComfoConnect, discover_bridges
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/__init__.py", line 3, in <module>
    from .bridge import Bridge  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 27, in <module>
    from .protobuf import zehnder_pb2
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/protobuf/zehnder_pb2.py", line 15, in <module>
    import nanopb.generator.proto.nanopb_pb2 as nanopb__pb2
  File "/usr/local/lib/python3.12/site-packages/nanopb/generator/proto/nanopb_pb2.py", line 9, in <module>
    from google.protobuf import runtime_version as _runtime_version
ImportError: cannot import name 'runtime_version' from 'google.protobuf' (/usr/local/lib/python3.12/site-packages/google/protobuf/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/comfoconnect/__init__.py", line 8, in <module>
    from aiocomfoconnect import ComfoConnect, discover_bridges
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/__init__.py", line 3, in <module>
    from .bridge import Bridge  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 27, in <module>
    from .protobuf import zehnder_pb2
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/protobuf/zehnder_pb2.py", line 15, in <module>
    import nanopb.generator.proto.nanopb_pb2 as nanopb__pb2
  File "/usr/local/lib/python3.12/site-packages/nanopb/generator/proto/nanopb_pb2.py", line 9, in <module>
    from google.protobuf import runtime_version as _runtime_version
ImportError: cannot import name 'runtime_version' from 'google.protobuf' (/usr/local/lib/python3.12/site-packages/google/protobuf/__init__.py)

**Comment by breinonline** [comment]
The same error here.

**Comment by Mercury-pl** [comment]
I thought that I did something wrong, as I was changing IP of my device. Same here 
`2024-09-24 20:32:53.914 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'comfoconnect': Unable to import component: cannot import name 'runtime_version' from 'google.protobuf' (/usr/local/lib/python3.12/site-packages/google/protobuf/__init__.py)`

**Comment by Revilo91** [comment]
duplicate #77
