### ISSUE TITLE
Local connection lost when WAN is down, error flooding

### ISSUE THREAD

**Issue by N3rdix** [michaelarnauts/home-assistant-comfoconnect#87]
Maybe a similar root cause like #43 but I observe a flood of error messages in the HA log when my internet connection goes down.
Last night there was a scheduled maintenance which caused hundred thousands of errors like these.

It seems the integration cannot recover from that state itself, reloading the integration doesn't fix it. The only way stopping the flood is pushing the small reconnect button on the LAN-C (or restarting the whole ComfoairQ).

Do you see any chance to analyze why this happens when the LAN-C loses internet connection?

**Most prominent error:**
```
Logger: homeassistant
Quelle: /usr/src/homeassistant/homeassistant/runner.py:147
Erstmals aufgetreten: 06:33:24 (2839 Vorkommnisse)
Zuletzt protokolliert: 06:43:44

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 218, in _process_message
    message = await self._read()
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 181, in _read
    msg_len_buf = await self._reader.readexactly(4)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 750, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 4 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 113, in _read_messages
    await self._process_message()
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 252, in _process_message
    raise AioComfoConnectNotConnected("The connection was closed.") from exc
aiocomfoconnect.exceptions.AioComfoConnectNotConnected: The connection was closed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 121, in _read_messages
    raise AioComfoConnectNotConnected("We have been disconnected") from exc
aiocomfoconnect.exceptions.AioComfoConnectNotConnected: We have been disconnected
```

```
Logger: homeassistant
Quelle: /usr/src/homeassistant/homeassistant/runner.py:147
Erstmals aufgetreten: 06:39:08 (47 Vorkommnisse)
Zuletzt protokolliert: 06:43:44

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/comfoconnect.py", line 81, in _reconnect_loop
    read_task = await self._connect(uuid)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiocomfoconnect/bridge.py", line 100, in _connect
    self._reader, self._writer = await asyncio.wait_for(asyncio.open_connection(self.host, self.PORT), TIMEOUT)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('10.10.30.50', 56747)

```

**Some warnings:**
```
Logger: aiocomfoconnect.bridge
Quelle: runner.py:189
Erstmals aufgetreten: 06:33:24 (2983 Vorkommnisse)
Zuletzt protokolliert: 06:43:39

Timeout while waiting for response from bridge
Failed to decode message: Error parsing message
Timeout while connecting to bridge 10.10.30.50

```

**Comment by astyrrian1** [comment]
Seeing a lot of this same issue.

**Comment by N3rdix** [comment]
Anything we can do to support finding the root cause @michaelarnauts?

**Comment by astyrrian1** [comment]
I factory reset my ComfoLan C device and I am no longer seeing the error flooding. I am wondering if maybe this occurs when there are too many devices paired to the Lan C?

**Comment by N3rdix** [comment]
Good point, I'll go and delete some connections I don't need primarily and report back if anything changes when disconnecting the WAN connection

**Comment by dkossako** [comment]
> Error doing job: Task exception was never retrieved (None)

I analyzed few GBs of HASS logs and it looks like issue starts always after this message. It happens after connectivity issues, but not always. 

In some cases when connection is broken, but integration will get the read timeout and/or connection timeout - it will survive and will be able to self heal. But when exception is not retrieved, integration runs into infinity loop of reconnects (it also generate a lot of network traffic).

**Comment by michaelarnauts** [comment]
The flood you describe starts after `Task exception was never retrieved`, as @dkossako found, which is the old connection handling failing to recover and leaving exceptions unretrieved.

That has been reworked since (michaelarnauts/aiocomfoconnect#66): one task reads from the socket, pending requests are failed when the connection drops, and a bridge that can't be reached is now reported as such instead of raising a bare `OSError` that nothing caught (michaelarnauts/aiocomfoconnect#83).

The fix is in aiocomfoconnect 0.2.1, which the integration will use from the next release. Closing this one since it has been open for a while, please open a new issue if you still see it after updating, with a debug log, and we will pick it up from there.
