### ISSUE TITLE
Comfoconnect not connecting - TCP Reset from server

### ISSUE THREAD

**Issue by Brewery-GIT** [michaelarnauts/home-assistant-comfoconnect#9]
Hello;

Thanks for all this work on this nice integration. I just got my comfoconnect lan c. I installed it and was able to connect to it from the Android App. When I want to use this integration, it fails on the first step ->

Enter a ComfoConnect LAN C bridge hostname or IP address below. 
Then it just keeps searching and searching.

When I sniff the connections, I constantly see "TCP RESET FROM SERVER"
So it seems the Comfoconnect LAN C won't let the integration connect.

Current setup:

LAN C IP: 10.10.40.19
HA IP: 10.10.80.254

Doesn't make a difference if I put the LAN C in the same network.(so with IP 10.10.80.19)

I also tried with the integrated addon as well, by adding it to the configuration.yaml file, but same issue:

2023-02-04 10:56:19.761 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: comfoconnect
2023-02-04 10:57:19.832 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: comfoconnect

Info:

Home Assistant 2023.2.1 
Supervisor 2023.01.1 
Operating System 9.5

Latest Addon.

Android App: Everything is green in "connection status"
Gateway version: U1.2.6
Android App Version: v1.7.0

I already factory reseted the LAN C unit, but no luck.
Perhaps you could point me in the direct where to look further? Not sure if this is related to the addon.
Thanks in advance.

**Comment by Gubbiej** [comment]
I have the same issue. When I try to connect to my zehnder comfo lan C it just keeps searching. It does auto discover the bridge but I dont get any further then that.

**Comment by Brewery-GIT** [comment]
You probably also get tcp resets...I acquired the installer password to see if it makes a difference but no luck.

I also tried fully disassociating the lan c from the app, but issue remains. For now I gave up, not much more I can try.

Let me know if logs or more info are needed

**Comment by michaelarnauts** [comment]
I have no idea what could be wrong here, but it looks like a networking issue. 

You could try enabling debug logging on the component. You can do that from the integration overview UI on Home Assistant itself.

![image](https://user-images.githubusercontent.com/1193779/230293327-5a58ed04-57cf-40f9-bbfd-953bacb1c8c4.png)

Try restarting Home Assistant so it can try to connect. You can then get the logs from the homeassistant.log file, or probably also trough the UI somewhere.

**Comment by sgeeurickx** [comment]
As the integration couldn't be setup correctly, I don't have access to that menu :-(

**Comment by michaelarnauts** [comment]
You can also enable logging trough to the configuration.yaml. Can't give you the exact config right now, but I hope Google or the HASS forums can help you find it.

**Comment by Brewery-GIT** [comment]
Apologies for delay in reply. I was able to get some further output. Now it just says: unknown error occured.

In the logs:

Deze fout is ontstaan door een aangepaste integratie.

Logger: aiohttp.server
Source: custom_components/comfoconnect/config_flow.py:131
Integration: Zehnder ComfoAir Q
First occurred: 20:59:22 (9 occurrences)
Last logged: 20:59:39

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/comfoconnect/config_flow.py", line 68, in async_step_user
    return await self._register()
  File "/config/custom_components/comfoconnect/config_flow.py", line 131, in _register
    await self.bridge.connect(self.local_uuid)
  File "/usr/local/lib/python3.10/site-packages/aiocomfoconnect/bridge.py", line 91, in connect
    self._reader, self._writer = await asyncio.open_connection(self.host, self.PORT)
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('10.10.80.50', 56747)

**Comment by michaelarnauts** [comment]
Do you still have this issue? I'm not sure what could prevent the connection to your bridge.

Can you ping 10.10.80.50 from your Home Assistant instance?

**Comment by Brewery-GIT** [comment]
> Do you still have this issue? I'm not sure what could prevent the connection to your bridge.
> 
> Can you ping 10.10.80.50 from your Home Assistant instance?

Hello,

No I have not made progress. I could ping:

10.10.80.254 to 10.10.80.50 (same network)
10.10.30.100 to 10.10.80.50 (user network to ha network)

Telnet connection on the port is also working. But not from the integration. It discovers the device automatically, but when adding it throws unspecified error.

I was following the other topic from Zollak as well, looks similar...

https://github.com/michaelarnauts/home-assistant-comfoconnect/issues/22#issue-1831039521

No idea what I can try...

**Comment by sgeeurickx** [comment]
Hi'
Since the latest release, I no longer have any problem connecting both my devices.
Thanks a lot for your work

**Comment by Brewery-GIT** [comment]
Small Update:

* I did not change any network settings
* I completely redeployed HA from scratch.

Now the integration works directly out of the box....
Thanks for your time on this integration, much appreciated.
